#!/usr/bin/env python3

import math
import sys


filename = sys.argv[1]
with open(str(filename), 'r') as f:
    numbers = [int(x) for x in f]
for num in numbers:
    i = 2
    flag = 0
    while i * i <= num:
        if i > 7:
            break
        if num % i:
            i += 1
            continue
        else:
            flag = 1
            print("{:d}={:d}*{:d}".format(num, num // i, i))
            break
    if flag:
        continue
    i = int(math.sqrt(num))
    while (i > (math.sqrt(num) // 2)):
        if num % i:
            i -= 1
            continue
        else:
            print("{:d}={:d}*{:d}".format(num, num // i, i))
            break
