#!/usr/bin/env python3

import math
import sys


filename = sys.argv[1]
with open(str(filename), 'r') as f:
    numbers = [int(x) for x in f]
for num in numbers:
    i = 2
    flag = 0
    while i * i <= num:
        if num % i:
           i += 1
           continue
        else:
           print("{:d}={:d}*{:d}".format(num, num // i, i))
           break