#!/usr/bin/env python3

import math
import sys


filename = sys.argv[1]
with open(str(filename), 'r') as f:
    num = int(f.readline())
i = 2
flag = 0
while i * i <= num:
    if num % i:
        i += 1
        continue
    else:
        print("{:d}={:d}*{:d}".format(num, num // i, i))
        break
